language: java

services:
  - docker

jdk:
  - openjdk14

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo "$DOCKER_PASSWORD" | docker login https://docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t docker.pkg.github.com/hyness/spring-cloud-config-server/test .
        - docker push docker.pkg.github.com/hyness/spring-cloud-config-server/test
    - stage: test
      script:
        - docker pull docker.pkg.github.com/hyness/spring-cloud-config-server/test
        - docker tag docker.pkg.github.com/hyness/spring-cloud-config-server/test hyness/spring-cloud-config-server
        - docker-compose -f examples/git/docker-compose.yml up -d
        - timeout 30 sh -c "until curl -o /dev/null -Isf localhost:8881/foo/development; do printf '.' && sleep 1; done"
        - timeout 30 sh -c "until curl -o /dev/null -Isf localhost:8882/foo/development; do printf '.' && sleep 1; done"
        - timeout 30 sh -c "until curl -o /dev/null -Isf localhost:8883/foo/development; do printf '.' && sleep 1; done"
        - "curl localhost:8881/foo/development | jq '.propertySources[0]' |
            jq 'contains({name: \"https://github.com/spring-cloud-samples/config-repo/foo-development.properties\"})'"
        - "curl localhost:8882/foo/development | jq '.propertySources[0]' |
            jq 'contains({name: \"https://github.com/spring-cloud-samples/config-repo/foo-development.properties\"})'"
        - "curl localhost:8883/foo/development | jq '.propertySources[0]' |
            jq 'contains({name: \"https://github.com/spring-cloud-samples/config-repo/foo-development.properties\"})'"
    - script:
        - docker pull docker.pkg.github.com/hyness/spring-cloud-config-server/test
        - docker tag docker.pkg.github.com/hyness/spring-cloud-config-server/test hyness/spring-cloud-config-server
        - docker-compose -f examples/native/docker-compose.yml up -d
        - timeout 30 sh -c "until curl -o /dev/null -Isf localhost:8881/foo/development; do printf '.' && sleep 1; done"
        - timeout 30 sh -c "until curl -o /dev/null -Isf localhost:8882/foo/development; do printf '.' && sleep 1; done"
        - timeout 30 sh -c "until curl -o /dev/null -Isf localhost:8883/foo/development; do printf '.' && sleep 1; done"
        - "curl localhost:8881/foo/development | jq '.propertySources[0]' |
            jq 'contains({name: \"https://github.com/spring-cloud-samples/config-repo/foo-development.properties\"})'"
        - "curl localhost:8882/foo/development | jq '.propertySources[0]' |
            jq 'contains({name: \"https://github.com/spring-cloud-samples/config-repo/foo-development.properties\"})'"
        - "curl localhost:8883/foo/development | jq '.propertySources[0]' |
            jq 'contains({name: \"https://github.com/spring-cloud-samples/config-repo/foo-development.properties\"})'"
